services:
  - type: web
    name: discord-ai-bot
    env: python
    plan: free
    buildCommand: pip install discord.py==2.4.0 google-genai==0.8.0 python-dotenv==1.0.0
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: BOT_PREFIX
        value: "!"